-- 程序数据库初始化脚本
-- 2016-03-15


--
-- 创建用户表 ( users ) --

CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(ID IDENTITY NOT NULL,
MOBILE VARCHAR(45) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
UPDATETIME TIMESTAMP,
CREATETIME TIMESTAMP NOT NULL,
STATUS TINYINT NOT NULL,
ROLE TINYINT NOT NULL,
PRIMARY KEY (ID),
UNIQUE (MOBILE));

